#!/usr/bin/env python3
"""
Utility functions for examples.
"""

import logging
import os
import re
import sys
from pathlib import Path
from typing import Any

# Set up logger
logger = logging.getLogger("kibana.examples")


def load_local_env() -> dict[str, str]:
    """
    Load environment variables from elastic-start-local/.env and .env.local.

    Reads ``.env`` for static defaults, then ``.env.local`` for runtime
    overrides (e.g. the API key regenerated by ``local-stack.sh``).
    Expands ``${VAR}`` and ``${VAR:-default}`` references, then injects
    into ``os.environ`` via ``setdefault`` so explicit env vars win.

    :return: Merged dictionary of environment variables
    """
    env_vars = {}

    env_dir = Path(__file__).parent.parent / "elastic-start-local"

    # Read .env (static defaults), then .env.local (runtime overrides)
    for filename in (".env", ".env.local"):
        env_file = env_dir / filename
        if env_file.exists():
            with open(env_file) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        # Strip surrounding quotes (single or double)
                        if (
                            len(value) >= 2
                            and value[0] == value[-1]
                            and value[0] in ('"', "'")
                        ):
                            value = value[1:-1]
                        env_vars[key] = value

    # Second pass: expand variable references
    for key, value in env_vars.items():
        env_vars[key] = _expand_variables(value, env_vars)

    # Inject into os.environ so all downstream os.getenv() calls see these values.
    # setdefault preserves any variable already set in the environment.
    for key, value in env_vars.items():
        os.environ.setdefault(key, value)

    return env_vars


def _expand_variables(value: str, env_vars: dict[str, str]) -> str:
    """
    Expand variable references in a string.

    Supports:
    - ${VAR_NAME} - Expands to the value of VAR_NAME
    - ${VAR_NAME:-default} - Uses default if VAR_NAME is not set

    :param value: String that may contain variable references
    :param env_vars: Dictionary of available variables
    :return: String with variables expanded
    """

    def replace_var(match):
        var_expr = match.group(1)

        # Check for default value syntax: VAR_NAME:-default
        if ":-" in var_expr:
            var_name, default_value = var_expr.split(":-", 1)
            return env_vars.get(var_name, default_value)
        else:
            # Simple variable reference
            var_name = var_expr
            return env_vars.get(var_name, match.group(0))

    try:
        expanded_value = re.sub(r"\$\{([^}]+)\}", replace_var, value)
        return expanded_value
    except Exception as e:
        logger.warning(f"Failed to expand variables in '{value}': {e}")
        return value


# Inject .env variables into os.environ at import time so integration tests
# and examples don't need any manual environment setup beyond this file.
load_local_env()


def get_kibana_config() -> tuple[str, tuple[str, str] | None, str | None]:
    """
    Get Kibana configuration from environment or local .env file.

    :return: Tuple of (kibana_url, basic_auth, api_key)
    """
    # Environment variables are populated from elastic-start-local/.env
    # at import time (via load_local_env), so os.getenv is the single lookup.
    kibana_url = os.getenv("KIBANA_URL") or os.getenv(
        "KIBANA_LOCAL_URL", "http://localhost:5601"
    )
    kibana_username = os.getenv("KIBANA_USERNAME")
    kibana_password = os.getenv("KIBANA_PASSWORD") or os.getenv("KIBANA_LOCAL_PASSWORD")
    api_key = os.getenv("KIBANA_API_KEY") or os.getenv("ES_LOCAL_API_KEY")

    # Prepare authentication
    basic_auth = None
    if kibana_username and kibana_password:
        basic_auth = (kibana_username, kibana_password)

    return kibana_url, basic_auth, api_key


def get_otel_config() -> dict[str, Any]:
    """
    Get OpenTelemetry configuration for OTLP integration.

    Configuration precedence:
    1. Environment variables (KIBANA_OTEL_*, OTEL_*)
    2. elastic-start-local/.env file
    3. Default values

    Returns:
        Dictionary containing:
        - enabled: bool
        - service_name: str
        - endpoint: str
        - headers: dict[str, str]
        - protocol: str
        - resource_attributes: dict[str, str]
        - logs_enabled: bool
        - logs_level: str
        - logs_loggers: list[str]
        - logs_endpoint: str | None
        - logs_protocol: str | None
    """
    # Load local environment variables first
    local_env = load_local_env()

    # Helper function to get config value with precedence
    def get_config_value(
        env_key: str, local_key: str | None = None, default: str = ""
    ) -> str:
        # 1. Environment variables have highest precedence
        env_value = os.getenv(env_key)
        if env_value is not None:
            return env_value

        # 2. Local .env file
        if local_key and local_key in local_env:
            return local_env[local_key]

        # 3. Default value
        return default

    # Get basic configuration
    enabled_str = get_config_value(
        "KIBANA_OTEL_ENABLED", "KIBANA_OTEL_ENABLED", "false"
    )
    enabled = enabled_str.lower() in ("true", "1", "yes", "on")

    service_name = get_config_value(
        "OTEL_SERVICE_NAME", "OTEL_SERVICE_NAME", "kibana-py-example"
    )

    endpoint = get_config_value(
        "OTEL_EXPORTER_OTLP_ENDPOINT",
        "OTEL_EXPORTER_OTLP_ENDPOINT",
        "http://localhost:8200",
    )

    protocol = get_config_value(
        "OTEL_EXPORTER_OTLP_PROTOCOL", "OTEL_EXPORTER_OTLP_PROTOCOL", "grpc"
    )

    # Handle authentication headers
    headers = {}

    # Get headers from environment or .env
    headers_str = get_config_value(
        "OTEL_EXPORTER_OTLP_HEADERS", "OTEL_EXPORTER_OTLP_HEADERS", ""
    )

    if headers_str:
        # Parse headers string (format: "key1=value1,key2=value2")
        # Handle quoted values
        try:
            # Remove outer quotes if present
            headers_str = headers_str.strip()
            if headers_str.startswith('"') and headers_str.endswith('"'):
                headers_str = headers_str[1:-1]

            for header_pair in headers_str.split(","):
                if "=" in header_pair:
                    key, value = header_pair.strip().split("=", 1)
                    # Expand variables in header values
                    expanded_value = _expand_variables(
                        value, {**local_env, **os.environ}
                    )
                    headers[key.strip()] = expanded_value
        except Exception as e:
            logger.warning(f"Failed to parse OTLP headers '{headers_str}': {e}")

    # If no headers configured, try to build authorization header from auth token
    if not headers:
        apm_token = get_config_value(
            "ELASTIC_APM_SECRET_TOKEN", "ELASTIC_APM_SECRET_TOKEN", ""
        )
        if apm_token:
            headers["authorization"] = f"Bearer {apm_token}"

    # Resource attributes with enhanced metadata using proper semantic conventions
    resource_attributes = {
        "service.name": service_name,
        "service.version": _get_kibana_py_version(),
        "service.language.name": "python",
        "service.language.version": _get_python_version(),
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.language": "python",
        "telemetry.sdk.version": _get_opentelemetry_version(),
    }

    # Add custom resource attributes from environment
    for key, value in os.environ.items():
        if key.startswith("OTEL_RESOURCE_ATTRIBUTES_"):
            attr_name = (
                key[len("OTEL_RESOURCE_ATTRIBUTES_") :].lower().replace("_", ".")
            )
            resource_attributes[attr_name] = value

    # Log forwarding configuration — defaults to following traces (enabled)
    # unless explicitly overridden via KIBANA_OTEL_LOGS_ENABLED
    logs_enabled_str = get_config_value(
        "KIBANA_OTEL_LOGS_ENABLED", "KIBANA_OTEL_LOGS_ENABLED", ""
    )
    if logs_enabled_str:
        logs_enabled = logs_enabled_str.lower() in ("true", "1", "yes", "on")
    else:
        logs_enabled = enabled

    logs_level = get_config_value(
        "KIBANA_OTEL_LOGS_LEVEL", "KIBANA_OTEL_LOGS_LEVEL", "INFO"
    )

    # Parse logger names from comma-separated string
    logs_loggers_str = get_config_value(
        "KIBANA_OTEL_LOGS_LOGGERS", "KIBANA_OTEL_LOGS_LOGGERS", "kibana,kibana.examples"
    )
    logs_loggers = [
        name.strip() for name in logs_loggers_str.split(",") if name.strip()
    ]

    # Log-specific endpoint (optional override)
    logs_endpoint = (
        get_config_value(
            "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT", "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT", ""
        )
        or None
    )

    # Log-specific protocol (optional override)
    logs_protocol = (
        get_config_value(
            "OTEL_EXPORTER_OTLP_LOGS_PROTOCOL", "OTEL_EXPORTER_OTLP_LOGS_PROTOCOL", ""
        )
        or None
    )

    return {
        "enabled": enabled,
        "service_name": service_name,
        "endpoint": endpoint,
        "headers": headers,
        "protocol": protocol,
        "resource_attributes": resource_attributes,
        "logs_enabled": logs_enabled,
        "logs_level": logs_level,
        "logs_loggers": logs_loggers,
        "logs_endpoint": logs_endpoint,
        "logs_protocol": logs_protocol,
    }


def should_enable_telemetry() -> bool:
    """
    Determine if telemetry should be enabled based on configuration.

    Returns:
        True if telemetry should be enabled, False otherwise
    """
    config = get_otel_config()
    return config["enabled"]


def _get_kibana_py_version() -> str:
    """Get the kibana-py version."""
    try:
        from kibana._version import __versionstr__

        return __versionstr__
    except ImportError:
        return "unknown"


def _get_python_version() -> str:
    """Get the Python version."""
    import sys

    return f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"


def _get_opentelemetry_version() -> str:
    """Get the OpenTelemetry SDK version."""
    try:
        # Try to get the version from the opentelemetry-sdk package
        try:
            import importlib.metadata

            return importlib.metadata.version("opentelemetry-sdk")
        except (ImportError, Exception):
            # Fallback: try to get from opentelemetry-api
            try:
                import importlib.metadata

                return importlib.metadata.version("opentelemetry-api")
            except (ImportError, Exception):
                # Last resort: try to get from the module itself
                try:
                    from opentelemetry import __version__

                    return __version__
                except (ImportError, AttributeError):
                    return "unknown"
    except Exception:
        return "unknown"


def _validate_endpoint_format(endpoint: str) -> bool:
    """
    Validate OTLP endpoint format.

    :param endpoint: Endpoint URL to validate
    :return: True if valid, False otherwise
    """
    if not endpoint:
        return False

    # Basic URL validation
    import urllib.parse

    try:
        parsed = urllib.parse.urlparse(endpoint)
        return bool(parsed.scheme and parsed.netloc)
    except Exception:
        return False


def configure_example_telemetry(
    *, enabled: bool | None = None, logs_enabled: bool | None = None
) -> tuple[bool, bool]:
    """
    Configure OpenTelemetry for examples with OTLP integration.

    Args:
        enabled: Override telemetry enable/disable (None = auto-detect)
        logs_enabled: Override log forwarding enable/disable (None = auto-detect)

    Returns:
        Tuple of (traces_configured, logs_configured)
    """
    try:
        # Import here to avoid dependency issues
        from kibana.observability import configure_opentelemetry
    except ImportError:
        logger.debug(
            "OpenTelemetry not available. Install with: pip install kibana-py[observability]"
        )
        return False, False

    # Get configuration
    config = get_otel_config()

    # Override enabled states if provided
    if enabled is not None:
        config["enabled"] = enabled
    if logs_enabled is not None:
        config["logs_enabled"] = logs_enabled

    # If traces disabled, don't configure anything
    if not config["enabled"]:
        logger.debug("OpenTelemetry telemetry disabled")
        return False, False

    # Validate configuration
    validation_errors = _validate_otel_config(config)
    if validation_errors:
        for error in validation_errors:
            logger.warning(f"OpenTelemetry configuration error: {error}")
        return False, False

    try:
        # Test OTLP endpoint connectivity if possible
        if not _test_apm_connectivity(config["endpoint"], config["headers"]):
            logger.warning(
                f"OTLP endpoint not reachable at {config['endpoint']}, telemetry may not work"
            )
            # Continue anyway - server might be starting up

        # Prepare log forwarding parameters
        logs_config = {}
        if config["logs_enabled"]:
            logs_config["logs_enabled"] = True
            logs_config["logs_level"] = config["logs_level"]
            logs_config["logs_loggers"] = config["logs_loggers"]

            # Use log-specific endpoint if configured, otherwise don't pass it (inherit from traces)
            if config["logs_endpoint"]:
                logs_config["logs_endpoint"] = config["logs_endpoint"]

            # Use log-specific protocol if configured, otherwise don't pass it (inherit from traces)
            if config["logs_protocol"]:
                logs_config["logs_protocol"] = config["logs_protocol"]

        # Configure OpenTelemetry with log forwarding support
        configure_opentelemetry(
            enabled=True,
            service_name=config["service_name"],
            exporter="otlp",
            endpoint=config["endpoint"],
            headers=config["headers"],
            protocol=config["protocol"],
            **logs_config,
        )

        traces_configured = True
        logs_configured = config["logs_enabled"]

        if logs_configured:
            logger.info(
                f"OpenTelemetry configured with traces and logs for OTLP endpoint: {config['endpoint']}"
            )
        else:
            logger.info(
                f"OpenTelemetry configured with traces only for OTLP endpoint: {config['endpoint']}"
            )

        return traces_configured, logs_configured

    except Exception as e:
        logger.error(f"Failed to configure OpenTelemetry: {e}")
        return False, False


def _validate_log_level(log_level: str) -> bool:
    """
    Validate log level string.

    :param log_level: Log level to validate
    :return: True if valid, False otherwise
    """
    valid_levels = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
    return log_level.upper() in valid_levels


def _validate_logger_names(logger_names: list[str]) -> list[str]:
    """
    Validate logger names and return any invalid ones.

    :param logger_names: List of logger names to validate
    :return: List of invalid logger names
    """
    invalid_names = []

    for name in logger_names:
        # Logger names should be non-empty strings
        if not name or not isinstance(name, str):
            invalid_names.append(str(name))
            continue

        # Logger names should not contain invalid characters
        # Allow alphanumeric, dots, underscores, and hyphens
        import re

        if not re.match(r"^[a-zA-Z0-9._-]+$", name):
            invalid_names.append(name)

    return invalid_names


def _validate_otel_config(config: dict[str, Any]) -> list[str]:
    """
    Validate OpenTelemetry configuration.

    :param config: Configuration dictionary
    :return: List of validation error messages
    """
    errors = []

    # Validate endpoint format
    if not _validate_endpoint_format(config["endpoint"]):
        errors.append(f"Invalid OTLP endpoint format: {config['endpoint']}")

    # Validate service name
    if not config["service_name"] or not config["service_name"].strip():
        errors.append("Service name cannot be empty")

    # Validate protocol
    valid_protocols = ["grpc", "http/protobuf"]
    if config["protocol"] not in valid_protocols:
        errors.append(
            f"Invalid protocol '{config['protocol']}', must be one of: {valid_protocols}"
        )

    # Validate log forwarding configuration if enabled
    if config.get("logs_enabled", False):
        # Validate log level
        if not _validate_log_level(config.get("logs_level", "")):
            errors.append(
                f"Invalid log level '{config.get('logs_level')}', must be one of: DEBUG, INFO, WARNING, ERROR, CRITICAL"
            )

        # Validate logger names
        invalid_loggers = _validate_logger_names(config.get("logs_loggers", []))
        if invalid_loggers:
            errors.append(f"Invalid logger names: {invalid_loggers}")

        # Validate logs endpoint if specified
        logs_endpoint = config.get("logs_endpoint")
        if logs_endpoint and not _validate_endpoint_format(logs_endpoint):
            errors.append(f"Invalid logs endpoint format: {logs_endpoint}")

        # Validate logs protocol if specified
        logs_protocol = config.get("logs_protocol")
        if logs_protocol and logs_protocol not in valid_protocols:
            errors.append(
                f"Invalid logs protocol '{logs_protocol}', must be one of: {valid_protocols}"
            )

    return errors


def _test_apm_connectivity(endpoint: str, headers: dict[str, str]) -> bool:
    """
    Test connectivity to OTLP endpoint.

    :param endpoint: OTLP endpoint
    :param headers: Authentication headers
    :return: True if server is reachable, False otherwise
    """
    try:
        import urllib.parse
        import urllib.request

        # Parse endpoint to get base URL
        parsed = urllib.parse.urlparse(endpoint)

        # For gRPC endpoints, we can't easily test connectivity
        # For HTTP endpoints, we could try a health check
        if parsed.scheme in ("http", "https"):
            # Try to connect with a short timeout
            req = urllib.request.Request(f"{parsed.scheme}://{parsed.netloc}/")

            # Add headers if provided
            for key, value in headers.items():
                req.add_header(key, value)

            with urllib.request.urlopen(req, timeout=2):
                return True
        else:
            # For gRPC or other protocols, assume connectivity
            return True

    except Exception as e:
        logger.debug(f"OTLP connectivity test failed: {e}")
        return False


def print_telemetry_info() -> None:
    """Print telemetry configuration information with masked tokens."""
    config = get_otel_config()

    print("=== Telemetry Configuration ===")
    print(f"Traces Enabled: {config['enabled']}")
    print(f"Service Name: {config['service_name']}")
    print(f"OTLP Endpoint: {config['endpoint']}")
    print(f"Protocol: {config['protocol']}")

    # Log forwarding configuration
    print(f"Log Forwarding Enabled: {config['logs_enabled']}")
    if config["logs_enabled"]:
        print(f"Log Level: {config['logs_level']}")
        print(f"Log Loggers: {', '.join(config['logs_loggers'])}")

        if config["logs_endpoint"]:
            print(f"Logs Endpoint: {config['logs_endpoint']}")
        else:
            print("Logs Endpoint: (inherits from traces)")

        if config["logs_protocol"]:
            print(f"Logs Protocol: {config['logs_protocol']}")
        else:
            print("Logs Protocol: (inherits from traces)")

    # Display headers with masked tokens
    if config["headers"]:
        print("Headers:")
        for key, value in config["headers"].items():
            if key.lower() in ("authorization", "auth", "token"):
                # Mask sensitive values - show first 10 and last 4 characters
                if len(value) > 14:
                    masked_value = f"{value[:10]}...{value[-4:]}"
                else:
                    masked_value = "***"
                print(f"  {key}: {masked_value}")
            else:
                print(f"  {key}: {value}")
    else:
        print("Headers: None")

    # Check if .env file exists
    env_file = Path(__file__).parent.parent / "elastic-start-local" / ".env"
    if env_file.exists():
        print(f"✅ Local .env file found: {env_file}")
    else:
        print(f"❌ Local .env file not found: {env_file}")

    print("=" * 32)
    print()


def cleanup_telemetry() -> None:
    """
    Implement automatic cleanup on example exit.
    Ensure proper OpenTelemetry shutdown sequence.
    Handle cleanup errors gracefully.
    """
    try:
        # Import here to avoid dependency issues
        from opentelemetry import trace

        # Get the current tracer provider
        tracer_provider = trace.get_tracer_provider()

        # If it's an SDK tracer provider, shut it down properly
        if hasattr(tracer_provider, "shutdown"):
            logger.debug("Shutting down OpenTelemetry tracer provider")
            tracer_provider.shutdown()

    except ImportError:
        # OpenTelemetry not available, nothing to clean up
        logger.debug("OpenTelemetry not available, no cleanup needed")
    except Exception as e:
        # Handle cleanup errors gracefully - never fail the example
        logger.debug(f"Error during telemetry cleanup: {e}")


def setup_telemetry_cleanup() -> None:
    """
    Set up automatic telemetry cleanup on example exit.
    Registers cleanup function to run when the process exits.
    """
    import atexit

    # Register cleanup function to run on exit
    atexit.register(cleanup_telemetry)


def should_cleanup(prompt: str = "Delete created resources? (y/N): ") -> bool:
    """
    Determine whether to clean up resources created by an example.

    When ``--cleanup`` is passed on the command line, resources are deleted
    automatically.  When ``--no-cleanup`` is passed, resources are kept.
    If neither flag is present the user is prompted interactively.

    :param prompt: Message shown when prompting interactively
    :return: True if resources should be deleted
    """
    if "--cleanup" in sys.argv:
        return True
    if "--no-cleanup" in sys.argv:
        return False
    return input(prompt).lower().strip() == "y"


def create_kibana_client():
    """
    Create a Kibana client with automatic configuration detection.

    :return: Configured Kibana client
    """
    from kibana import Kibana

    kibana_url, basic_auth, api_key = get_kibana_config()

    print(f"🔗 Connecting to Kibana: {kibana_url}")

    # Prefer API key over basic auth
    if api_key:
        print("🔑 Using API key authentication")
        return Kibana(kibana_url, api_key=api_key)
    elif basic_auth:
        print(f"🔐 Using basic authentication (user: {basic_auth[0]})")
        return Kibana(kibana_url, basic_auth=basic_auth)
    else:
        print("⚠️  No authentication configured - using anonymous access")
        return Kibana(kibana_url)


def create_async_kibana_client():
    """
    Create an AsyncKibana client with automatic configuration detection.

    :return: Configured AsyncKibana client
    """
    from kibana import AsyncKibana

    kibana_url, basic_auth, api_key = get_kibana_config()

    print(f"🔗 Connecting to Kibana (async): {kibana_url}")

    # Prefer API key over basic auth
    if api_key:
        print("🔑 Using API key authentication")
        return AsyncKibana(kibana_url, api_key=api_key)
    elif basic_auth:
        print(f"🔐 Using basic authentication (user: {basic_auth[0]})")
        return AsyncKibana(kibana_url, basic_auth=basic_auth)
    else:
        print("⚠️  No authentication configured - using anonymous access")
        return AsyncKibana(kibana_url)


def demonstrate_structured_logging():
    """
    Demonstrate structured logging best practices with log forwarding.

    Shows how to use structured logging with custom attributes that will be
    forwarded to OTLP endpoint when log forwarding is enabled.
    """
    # Get a logger for demonstration
    demo_logger = logging.getLogger("kibana.examples.demo")

    print("=== Structured Logging Examples ===")
    print(
        "The following log messages will be forwarded to OTLP endpoint if log forwarding is enabled:"
    )
    print()

    # Example 1: Basic structured logging with extra attributes
    demo_logger.info(
        "Kibana API request started",
        extra={
            "api_method": "POST",
            "api_path": "/api/actions/connector",
            "request_id": "req_12345",
            "user_id": "user_67890",
        },
    )

    # Example 2: Error logging with context
    demo_logger.error(
        "Failed to create connector",
        extra={
            "api_method": "POST",
            "api_path": "/api/actions/connector",
            "error_code": "VALIDATION_ERROR",
            "connector_type": ".index",
            "request_id": "req_12345",
            "duration_ms": 150,
        },
    )

    # Example 3: Performance logging
    demo_logger.warning(
        "Slow API response detected",
        extra={
            "api_method": "GET",
            "api_path": "/api/status",
            "duration_ms": 5000,
            "threshold_ms": 1000,
            "request_id": "req_12346",
        },
    )

    # Example 4: Business logic logging
    demo_logger.info(
        "Connector created successfully",
        extra={
            "connector_id": "conn_abc123",
            "connector_type": ".index",
            "connector_name": "My Index Connector",
            "space_id": "default",
            "created_by": "user_67890",
            "request_id": "req_12345",
        },
    )

    print("✅ Structured logging examples completed")
    print("📊 Check your observability backend for correlated logs and traces")
    print()


def demonstrate_log_trace_correlation():
    """
    Demonstrate log-trace correlation when both tracing and log forwarding are enabled.

    Shows how logs automatically include trace and span IDs for correlation in your observability backend.
    """
    try:
        from kibana.observability import span_context
    except ImportError:
        print("⚠️  OpenTelemetry not available - trace correlation not possible")
        return

    print("=== Log-Trace Correlation Example ===")

    # Use span_context to create a span that is set as the current span,
    # enabling automatic trace/span ID injection into logs
    with span_context(
        "example_operation",
        attributes={
            "operation.type": "api_request",
            "operation.name": "create_connector",
            "service.component": "kibana_client",
        },
    ) as span:
        if span is None:
            print("⚠️  Could not create span - tracing may not be enabled")
        else:
            # Get a logger for demonstration
            demo_logger = logging.getLogger("kibana.examples.correlation")

            print("Creating a span and logging within it...")

            # Log messages within the span context will automatically include trace/span IDs
            demo_logger.info(
                "Starting connector creation process",
                extra={
                    "operation": "create_connector",
                    "step": "validation",
                    "connector_type": ".index",
                },
            )

            # Simulate some work
            import time

            time.sleep(0.1)

            demo_logger.info(
                "Connector validation completed",
                extra={
                    "operation": "create_connector",
                    "step": "creation",
                    "validation_result": "success",
                },
            )

            # Simulate more work
            time.sleep(0.1)

            demo_logger.info(
                "Connector created successfully",
                extra={
                    "operation": "create_connector",
                    "step": "completion",
                    "connector_id": "conn_demo_123",
                    "duration_ms": 200,
                },
            )

            print("✅ Log-trace correlation example completed")
            print(
                "🔗 Logs within the span will include trace and span IDs in your observability backend"
            )

    print()


def demonstrate_log_level_filtering():
    """
    Demonstrate log level filtering behavior.

    Shows how different log levels are handled based on the configured log forwarding level.
    """
    print("=== Log Level Filtering Example ===")

    config = get_otel_config()
    current_level = config.get("logs_level", "WARNING")

    print(f"Current log forwarding level: {current_level}")
    print("Demonstrating different log levels:")
    print()

    # Get a logger for demonstration
    demo_logger = logging.getLogger("kibana.examples.filtering")

    # Demonstrate all log levels
    demo_logger.debug(
        "Debug message - detailed information for troubleshooting",
        extra={"log_level_demo": True, "level": "DEBUG"},
    )

    demo_logger.info(
        "Info message - general information about application flow",
        extra={"log_level_demo": True, "level": "INFO"},
    )

    demo_logger.warning(
        "Warning message - something unexpected happened but not critical",
        extra={"log_level_demo": True, "level": "WARNING"},
    )

    demo_logger.error(
        "Error message - something went wrong and needs attention",
        extra={"log_level_demo": True, "level": "ERROR"},
    )

    demo_logger.critical(
        "Critical message - serious error that may cause application failure",
        extra={"log_level_demo": True, "level": "CRITICAL"},
    )

    print(
        f"📊 Only logs at {current_level} level and above will be forwarded to OTLP endpoint"
    )
    print("💡 Adjust KIBANA_OTEL_LOGS_LEVEL environment variable to change filtering")
    print()


def demonstrate_logger_selection():
    """
    Demonstrate logger selection for log forwarding.

    Shows how different loggers can be configured for forwarding.
    """
    print("=== Logger Selection Example ===")

    config = get_otel_config()
    configured_loggers = config.get("logs_loggers", [])

    print(f"Configured loggers for forwarding: {', '.join(configured_loggers)}")
    print("Demonstrating different logger usage:")
    print()

    # Demonstrate different loggers
    loggers_to_test = [
        ("kibana", "Main kibana client logger"),
        ("kibana.examples", "Examples logger"),
        ("kibana.actions", "Actions API logger"),
        ("kibana.saved_objects", "Saved Objects API logger"),
        ("my_app", "Custom application logger"),
        ("my_app.module", "Custom module logger"),
    ]

    for logger_name, description in loggers_to_test:
        test_logger = logging.getLogger(logger_name)
        forwarded = logger_name in configured_loggers or any(
            logger_name.startswith(configured) for configured in configured_loggers
        )

        status = "✅ FORWARDED" if forwarded else "❌ NOT FORWARDED"

        test_logger.info(
            f"Test message from {logger_name}",
            extra={
                "logger_demo": True,
                "logger_name": logger_name,
                "will_be_forwarded": forwarded,
            },
        )

        print(f"  {logger_name}: {description} - {status}")

    print()
    print(
        "💡 Configure KIBANA_OTEL_LOGS_LOGGERS environment variable to change logger selection"
    )
    print("   Example: KIBANA_OTEL_LOGS_LOGGERS=kibana,my_app")
    print()


def run_structured_logging_examples():
    """
    Run all structured logging examples and best practices demonstrations.

    This function provides a comprehensive demonstration of structured logging
    capabilities when log forwarding is enabled.
    """
    print("🚀 Running Structured Logging Examples")
    print("=" * 50)
    print()

    # Check if log forwarding is enabled
    config = get_otel_config()
    if config["logs_enabled"]:
        print("✅ Log forwarding is ENABLED - logs will be sent to OTLP endpoint")
        print(f"📊 OTLP Endpoint: {config['endpoint']}")
        print(f"📈 Log Level: {config['logs_level']}")
        print(f"📝 Loggers: {', '.join(config['logs_loggers'])}")
    else:
        print("⚠️  Log forwarding is DISABLED - logs will only appear locally")
        print("💡 Set KIBANA_OTEL_LOGS_ENABLED=true to enable log forwarding")

    print()

    # Run all demonstrations
    demonstrate_structured_logging()
    demonstrate_log_level_filtering()
    demonstrate_logger_selection()
    demonstrate_log_trace_correlation()

    print("🎉 All structured logging examples completed!")
    print("📚 Best Practices Summary:")
    print("  • Use structured logging with 'extra' parameters for rich context")
    print("  • Include request IDs, user IDs, and operation context in logs")
    print("  • Use appropriate log levels (ERROR for failures, WARNING for issues)")
    print("  • Create spans around operations for automatic log-trace correlation")
    print("  • Configure logger names to control which logs are forwarded")
    print("  • Use consistent attribute naming across your application")
    print()


def print_config_info():
    """Print configuration information for debugging."""
    kibana_url, basic_auth, api_key = get_kibana_config()

    print("=== Configuration Information ===")
    print(f"Kibana URL: {kibana_url}")

    if api_key:
        print(
            f"API Key: {api_key[:10]}..."
            if len(api_key) > 10
            else f"API Key: {api_key}"
        )
    elif basic_auth:
        print(f"Basic Auth: {basic_auth[0]} / {'*' * len(basic_auth[1])}")
    else:
        print("Authentication: None")

    # Check if local .env exists
    env_file = Path(__file__).parent.parent / "elastic-start-local" / ".env"
    if env_file.exists():
        print(f"✅ Local .env file found: {env_file}")
    else:
        print(f"❌ Local .env file not found: {env_file}")

    print("=" * 35)
    print()


if __name__ == "__main__":
    # Test the configuration
    print_config_info()

    try:
        client = create_kibana_client()
        print("✅ Kibana client created successfully")
        client.close()
    except Exception as e:
        print(f"❌ Failed to create Kibana client: {e}")
